name: main

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs: 
  build-net:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'

      - name: Create Build Directory
        run: mkdir dist-net,dist-netcore

      - name: Build .Net version
        run: | 
          msbuild.exe SourcetrailDotnetIndexer.sln /t:SourcetrailDotnetIndexer /nologo /p:platform="x64" /p:configuration="Release" /p:OutputPath="..\dist-net"

      - name: Build .Net Core version
        run: dotnet publish SourcetrailDotnetCoreIndexer\SourcetrailDotnetCoreIndexer.csproj -c Release -o "dist-netcore" -r win-x64 --nologo --self-contained false

      - name: Packing .Net artifact
        run: |
          7zip SourcetrailDotnetIndexer-win-x64.zip .\dist-net\*

      - name: Packing .Net Core artifact
        run: |
          7zip SourcetrailDotnetCoreIndexer-win-x64.zip .\dist-netcore\*

      - name: Uploading artifacts
        uses: actions/upload-artifact@v2
        with:
          name: BUILD
          path: ./*-win-x64.zip

  release:
    runs-on: ubuntu-latest
    needs: build-net
    if: ${{ github.event_name != 'pull_request' }}
    steps:
      - name: Create github release 
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: ${{ !startsWith(github.ref, 'refs/tags/v') }}
          prerelease: false

      - uses: actions/download-artifact@v2
        with:
          name: BUILD
          path: BUILD

      - name: Uploading artifacts to release
        uses: alexellis/upload-assets@0.2.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          asset_paths: '["./BUILD/*"]'